apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: integration-clusters
  namespace: reverse-words-int
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      env: int